swagger: "2.0"
info:
  title: Echo API
  description: Simple Rest Echo
  version: "1.0.0"
host: "localhost:8080"
schemes:
  - http
basePath: /v1
produces:
  - application/json
tags:
  - name: Echo
paths:
  /echo/{message}:
    get:
      tags:
        - Echo
      description: "Returns the 'message' to the caller"
      operationId: "echo"
      parameters:
        - name: message
          description: message
          in: path
          type: string
          required: true
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/EchoResponse"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/Error"
definitions:
  EchoResponse:
    required:
      - message
    properties:
      message:
        type: string
  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
